### ISSUE TITLE
can't i test the project in local server?

### ISSUE THREAD

**Issue by fuchao2012** [ujjalsuttradhar/ci_boilerplate_management#1]
got the 404 page called

>  /adminlte2/dashboard was not found on this server

adminlte2 is my project name

mac env

anything more need to config in the base_url in the local environment?

**Comment by ujjalsuttradhar** [comment]
Sorry for this inconvenience. Because of the .gitignore, config.php and database.php was not added to the repository. Please pull your repository and update base_url and database credentials.

Thanks for your interest.
