### ISSUE TITLE
base_url issue

### ISSUE THREAD

**Issue by shawdren** [ujjalsuttradhar/ci_boilerplate_management#2]
Hi, thanks for you share this project, as beginner of php and codeignitor, I have had encounter an issue after cloned code and configged following the document. which I had set base_url = 'http://localhost/manageVC/', the route cannot works, because it is missing index.php. But when I set base_url = 'http://localhost/manageVC/index.php', the resource files are cannot included, because the index.php is redundant one. for example 'http://localhost/manageVC/index.php/resources/css/datatables/dataTables.bootstrap.css' this is link is not work. So what's base_url value should be work for route and resource files? thank you.

**Comment by ujjalsuttradhar** [comment]
Seems your .htaccess is not working. _index.php_ shouldn't be in base_url. So, make sure that the .htaccess file is working. 

Troubleshooting:
1. Make sure that there is a .htaccess file in project root folder.
2. Make sure that your apache/nginx config has AllowOverride property (Depending on your server, search for how to get htaccess working)  
- Let me know your findings. 

Thank you very much for your interest.

-Ujjal

**Comment by shawdren** [comment]
yes, it's because the AllowOverride property is not grant on my apache server, now it works. 
Thank you so much!
